name: Test Gemmi

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-11
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install gemmi package
        run: |
          pip install gemmi

      - name: Import gemmi.cif
        run: |
          python -c "import gemmi.cif"
        
